### ISSUE TITLE
Failed to remove release saying "Not Found" even though it identified the release. 

### ISSUE THREAD

**Issue by Suresh-rc** [dev-drprasad/delete-tag-and-release#34] opened 2023-05-09 08:51 UTC
Run dev-drprasad/delete-tag-and-release@v1.0
🏷 given tag is "v0.5.7"
📕 given repo is "my-org/my-repo"
📕 delete releases is set to "true"
🍻 found 1 releases to delete
Error: 🛑 failed to delete release with id "11558844"  <- Not Found

What would be missing here?
The release is getting created in same job. Suspecting that might be a problem, I tried to Checkout repository before this stop. Still no avail.

**Comment by thadguidry** [comment] 2023-05-10 01:10
Very likely the problem (and not a bug), since release ID's are only created upon a successful release creation event AND the GitHub API has returned a success to the release agent (or library you are using in your action).

However, you might use 2 jobs where job 2 needs job 1 to be successful?
What did you intend for your workflow to look like?
Did you want it to create a release in 1 job , and then using a 2nd job run `delete-tag-and-release` ?  If so, perhaps you want to modify your workflow file so that you have 2 jobs, but ensure that job 2 has a `needs` job 1 to be successful.  Otherwise, jobs run in parallel on GitHub Actions.  See: https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs  and also if you want canceling in-progress jobs (and have complex workflows and groups) then please read this: https://docs.github.com/en/actions/using-jobs/using-concurrency

**Comment by Suresh-rc** [comment] 2023-05-10 06:36
Thanks for response. Let me clarify my use case more. 
So there is automated build process and workflow looks like this.
What it does is highlevel.
1. Create a release and tag for the repo.
2. Run some build scripts and docker push and other stuff with above tag.
3. If any of the step in #2 fails, just delete the release and tag created before.

Currently what is happening is if my steps fails in #2 stage The release tag still persist and I want to clear that if this happens.
So according to me the release tag nicely exist when we reach to last step that is delete tag and release.

I mean it shouldnt be problem within one job.

      `name: "Create Release"
        id: create_release
        uses: actions/create-release@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_RELEASE_VERSION }}
          release_name: v${{env.NEW_RELEASE_VERSION }}
          body: Release created by GitHub Action.
          draft: false
          prerelease: false`

#Do some docker build and push action. (Long process >5mins)

        `name: Reverse release if failed
        if:  failure()
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          github_token: ${{ secrets.GHTOKEN }}
          tag_name: v${{ env.NEW_RELEASE_VERSION }}
          delete_release: true
        continue-on-error: true # this should be remvoved if I can fix flow.`

**Comment by thadguidry** [comment] 2023-05-11 07:55
Right, it should not be a problem... but for some reason it is.
I'd turn on more logging and echo out your env variables.  Read the GitHub Actions documentation more.
This will help you narrow down why the release id is not being found.
Find it yourself even.  comment out your stage 2 and 3... then run the workflow...
Can you find the release id and see it listed when you go to the GitHub UI and click on your projects Tags -> Releases ?

Also...
Most folks ensure their build is successful FIRST (CI) ... THEN create a tag and do a release (CD).
CI -> CD
I'd suggest to do the same.  This also enforces good CI ... to happen first ... before good CD.
https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization

**Comment by thadguidry** [comment] 2023-05-11 08:00
Finally... that Action ... @actions/create-release is not even maintained anymore by GitHub... So I'd suggest you move to using one of the other recommended actions they note on their README.  https://github.com/actions/create-release

Many folks like and use @marvinpinto/action-automatic-releases ... but you'll see the others in their README.  (or search the marketplace.

Good luck !
Closing as not a bug.  (release id not being created correctly for some reason and likely because the actions is using deprecated older GH Release API)

**Closed as completed by thadguidry** 2023-05-11 08:00 UTC

**Comment by Suresh-rc** [comment] 2023-05-11 08:29
Thanks for the help. I had this option in mind "_Most folks ensure their build is successful FIRST (CI) ... THEN create a tag and do a release (CD)._" but there were some usage for tag in Step 2.

So essentially I removed those dependencies and creating release tag in the end.

Will move away from create-release too as its not maintained anymore But its working all fine at the moment and not the reason of my problem.
Thanks for all the help.
